language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - MAGENTO_VERSION="magento-mirror-1.8.1.0"
  - MAGENTO_VERSION="magento-mirror-1.9.0.1"
  - MAGENTO_VERSION="magento-mirror-1.9.1.1"
  - MAGENTO_VERSION="magento-mirror-1.9.2.1"
  - MAGENTO_VERSION="magento-mirror-1.9.2.2"
  - MAGENTO_VERSION="magento-mirror-1.9.2.3"
  - MAGENTO_VERSION="magento-mirror-1.9.2.4"

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: 7.0
    - php: hhvm

script:
  - curl --retry 2 --retry-delay 5 -f -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash
